# Unified App Config

app:
  name: DevOps Simulator
  version: 3.0.0
  environment: ${DEPLOY_ENV}

features:
  auto_scaling: true
  ssl: true
  load_balancer: true
  backup: true
  hot_reload: true # Dev
  debug_mode: true # Dev
  ai_optimization: true # Experimental
